Problem-1


In [ ]:
#1 Initialize an empty array with size 2X2.
import numpy as np
a1 = np.empty([2,2])
print(a1.shape)

(2, 2)


In [ ]:
#2 Initialize an all one array with size 4X2.
import numpy as np
a1 = np.ones([4,2])
print(a1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3 Return a new array of given shape and type, filled with fill value.
import numpy as np
a1 = np.full((2, 4), 7)
print(a1)

[[7 7 7 7]
 [7 7 7 7]]


In [ ]:
#4 Return a new array of zeros with same shape and type as a given array.
import numpy as np
a1 = np.array([[2,3],
               [4,5]])
zeros = np.zeros_like(d)
print(zeros)

[[0 0]
 [0 0]]


In [1]:
#5. Return a new array of ones with same shape and type as a given array.
import numpy as np

arr = np.array([[3, 5, 7],
                [2, 4, 6]])

ones_arr = np.ones_like(arr)

print(ones_arr)

[[1 1 1]
 [1 1 1]]


In [4]:
from typing_extensions import Type
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np

new_list = [1, 2, 3, 4]

arr = np.array(new_list)

print(type(arr))

<class 'numpy.ndarray'>


Problem-2

In [5]:
#1 Create an array with values ranging from 10 to 49.
import numpy as np

arr = np.arange(10, 50)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.
import numpy as np

arr = np.arange(0, 9, 1)
matrix = np.reshape(arr, (3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#3 Create a 3X3 identity matrix.
import numpy as np

identity_matrix = np.eye(3,3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#4 Create a random array of size 30 and find the mean of the array.
import numpy as np

arr = np.random.random(30)
mean = np.mean(arr)
print(arr)
print(mean)

[0.01836653 0.92390047 0.87450407 0.99226054 0.22611035 0.76923304
 0.06553421 0.56839344 0.5501527  0.55376678 0.46514232 0.1970436
 0.37550848 0.70512201 0.15351406 0.19713378 0.69356646 0.99967741
 0.81017679 0.72227412 0.13484582 0.18956635 0.2752186  0.79053813
 0.10803258 0.75901307 0.12773005 0.86743666 0.74587139 0.39954454]
0.5086392771296344


In [12]:
#5 Create a 10X10 array with random values and find the minimum and maximum values.
import numpy as np

# create a 10x10 array with random values between 0 and 1
arr = np.random.random((10, 10))

# find minimum and maximum values
min_value = arr.min()
max_value = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Array:
 [[0.47626888 0.28440495 0.34957901 0.04159136 0.628771   0.79325537
  0.02797294 0.00902246 0.91955059 0.51624632]
 [0.55586799 0.29334988 0.43403257 0.42098529 0.7009385  0.31337249
  0.13516933 0.31744633 0.43621861 0.24796396]
 [0.55410788 0.37952985 0.19829182 0.0325723  0.12431408 0.75751013
  0.9303908  0.48752633 0.47545578 0.96767571]
 [0.74798586 0.76426153 0.2407948  0.02112527 0.38272723 0.64873558
  0.74579838 0.39247052 0.61407637 0.84239894]
 [0.58641049 0.18556522 0.26496207 0.99530256 0.35776138 0.39754987
  0.90167637 0.20325913 0.61607997 0.05851523]
 [0.84651022 0.70315577 0.34450372 0.68303959 0.72485433 0.28622735
  0.09511662 0.12066867 0.57803941 0.81027202]
 [0.18878022 0.91792401 0.73201339 0.69454067 0.41142054 0.36920934
  0.40033703 0.34162305 0.24721495 0.51299401]
 [0.14203719 0.1229858  0.55407843 0.03853358 0.91716725 0.48247415
  0.22860674 0.13553393 0.74786003 0.09290591]
 [0.03949731 0.97481217 0.75362094 0.05542934 0.35230535 0.32454379
  0.

In [13]:
#6 Create a zero array of size 10 and replace 5th element with 1.
import numpy as np

arr = np.zeros(10)

arr[4] = 1

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7 Reverse an array arr = [1,2,0,0,4,0].
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

reversed = arr[::-1]

print(reversed)

[0 4 0 0 2 1]


In [17]:
#8 Create a 2d array with 1 on border and 0 inside.
import numpy as np

arr = np.ones((3,3))
arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [18]:
#9 Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem-3

In [24]:
#1 Add the two array.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
add = x + y
print("Addition:\n", add)

Addition:
 [[ 6  8]
 [10 13]]


In [23]:
#2 Subtract the two array.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sub = x - y
print("\nSubtraction:\n", sub)


Subtraction:
 [[-4 -4]
 [-4 -3]]


In [26]:
#3 Multiply the array with any integers of your choice.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
mul = x * 99
print("\nMultiplication by 3:\n", mul)


Multiplication by 3:
 [[ 99 198]
 [297 495]]


In [28]:
#4 Find the square of each element of the array.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
square1 = x**2
square2 = y**2
square3 = v**2
square4 = w**2
print("\nSquare of each element in x array:\n", square1)
print("\nSquare of each element in y array:\n", square2)
print("\nSquare of each element in v array:\n", square3)
print("\nSquare of each element in w array:\n", square4)


Square of each element in x array:
 [[ 1  4]
 [ 9 25]]

Square of each element in y array:
 [[25 36]
 [49 64]]

Square of each element in v array:
 [ 81 100]

Square of each element in w array:
 [121 144]


In [31]:
#5 Find the dot product between: v(and)w ; x(and)v ; x(and)y.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product between v and w:", dot_vw)
print("Dot product between x and v:", dot_xv)
print("Dot product between x and y:\n", dot_xy)

Dot product between v and w: 219
Dot product between x and v: [29 77]
Dot product between x and y:
 [[19 22]
 [50 58]]


In [32]:
#6 Concatenate x(and)y along row and Concatenate v(and)w along column.
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)

print("Concatenate x and y along row:\n", concat_row)
print("Concatenate v and w along column:\n", concat_col)

Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [34]:
#7 Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
concat = np.concatenate((x, v))
print(concat)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Since x has 2d array and v is a 1d array numpy cannot concatenate them as their shape are incompatible. Also concatenation requires all dimensions except the concatenating axis to match since v doesnt have second dimension, the shapes do not align, so a ValueError occurs.

Problem-4

In [35]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)

print("A * A⁻¹ =\n", I)

A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [36]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("A*B =\n", AB)
print("B*A =\n", BA)
print("A*B == B*A ?", np.array_equal(AB, BA))

A*B =
 [[23 13]
 [51 29]]
B*A =
 [[36 44]
 [13 16]]
A*B == B*A ? False


In [37]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB_T = (np.dot(A, B)).T
B_T_A_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_T_A_T)
print("(AB)^T == B^T*A^T ?", np.array_equal(AB_T, B_T_A_T))

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T == B^T*A^T ? True


In [39]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

X = np.linalg.solve(A, B)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]


In [40]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]
